name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: nginx/Dockerfile
          tags: nginx:v2
          outputs: type=docker,dest=/tmp/nginx.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nginx.tar
          path: /tmp/nginx.tar
      -    
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: flask/Dockerfile
          tags: flask:v1
          outputs: type=docker,dest=/tmp/flask.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: flask.tar
          path: /tmp/flask.tar

  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          path: /tmp
      -
        name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: dockerplay.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: ${{ secrets.INVENTORY }}


      
  

    
