name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  

  Deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          path: /tmp
      -
        name: Run Ansible playbook
        uses: ministryofjustice/ansible-playbook-with-keyvault-action@v1.1
        with:
          ansible_playbook: dockerplay.yml
          keyvault_secret_name_ssh_privkey: ${{ secrets.SSH_PRIVATE_KEY }}
          ansible_inventory: ${{ secrets.INVENTORY }}


      
  

    
