name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  

  Deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          path: /tmp
      -
        uses: actions/checkout@v2
      -
        name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: dockerplay.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: ${{ secrets.INVENTORY }}
          


      
  

    
