name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 
  build-image-nginx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the nginx image
      run: docker build nginx --file nginx/Dockerfile --tag nginx:v2
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      
      
  build-image-flask1:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the flask image
      run: docker build flask --file flask/Dockerfile --tag flask:v1
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      
  save_kont:
    needs: [build-image-flask1,build-image-nginx]
    runs-on: ubuntu-latest
    steps:
    - name: Display structure of downloaded files
      run: ls -R

      
  

    
