name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  

  Deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          path: /tmp
      -
        name: Run Ansible playbook
        uses: actions/checkout@v2
        uses: arillso/action.playbook@0.0.4
        with:
          playbook: dockerplay.yml
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: ${{ secrets.INVENTORY }}
          user: ${{ secrets.USER }}


      
  

    
